### ISSUE TITLE
Fail to uncompress zip file of 111 Mb 

### ISSUE THREAD

**Issue by qburst-akhil** [glebdmitriew/node-unzip-2#23]
I am reading data from an ftp stream using ssh2 (The entire code is not shown)
`var readStream = sftp.createReadStream("/dir/filename.zip")
readStream.pipe(unzip.Parse())
          .on('entry', entry => {
            console.log(`Inside transform callback....`);
            s3Manipulator.writeStreamToBucket('bucket_nm', entry.path, entry)
          })
          .on('error', err => {
            console.log(`Error thrown streaming ${err}`);
          });`

I am running this from an ubuntu system it shows upload activity, but after a while the error callback is invoked. The error is given below:

`code:"Z_DATA_ERROR"
errno:-3
message:"invalid literal/lengths set"
stack:"Error: invalid literal/lengths set\n    at InflateRaw.zlibOnError (zlib.js:153:15)"
__proto__:Object {constructor: , name: "Error", message: "", …}`

I have no clue as to why this happens.
Any help is appreciated, thanks in advance.

**Comment by bi-kai** [comment]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
```
similar problem, but with above error.
my zip file is above 200MB, if i use small ones, it;s ok.

**Comment by bi-kai** [comment]
@qburst-akhil I'm using `decompress` module now, ant it's fine.
